config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home", :to => "static_pages#home"
  get  "/signup", :to => "users#new"
  post "/signup", :to => "users#create"
  get "/graph",  :to => "users#graph"
  get    "/login", :to => "sessions#new"
  post   "/login", :to => "sessions#create"
  delete "/logout", :to => "sessions#destroy"
  resources :users do
    get :search, :on => :collection
    member do
      get :following, :followers
    end
  end
  resources :microposts, :only => [:create, :destroy, :edit, :update]
  resources :account_activations, :only => [:edit]
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :events
  resources :subjects
  resources :relationships, :only => [:create, :destroy]
  resources :likes, :only => [:create, :destroy]
  resources :guest_sessions, :only => [:create]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      define_user
      @micropost = Micropost.new
      @feed_items = current_user.feed.page(params[:page]).per(7)
      @like_count = Like.where(:micropost_id => params[:micropost_id]).count
    end
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.haml
- provide(:title, "Home")
- if logged_in?
  .container.show-container
    .row
      %aside.col-md-3
        .fixed-sidebar
          %section.user_info
            = render "shared/user_info"
          %section.stats
            = render "shared/stats"
      .col-md-9
        - if @feed_items.any?
          .page-control= paginate @feed_items
          %h4 TimeLine
          %ol.microposts#area_microposts
            = render @feed_items

- else
  .top-container
    .left-container.column
      .container.text-container
        %h1 Welcome to DEPS
        %p DEPS helps you manage task and create schedules.
        %p Let's click the button below and create own account now.
        = link_to "Create Account", new_user_path, class: "btn btn-info btn-lg"
    .right-container.column
      .signup-container
        .col.form-box
          = form_with(scope: :session, url: login_path, local: true) do |f|
            .form-group
              =f.text_field :"email", class: "form-control", placeholder: "email-address"
            .form-group
              =f.text_field :password, class: "form-control", placeholder: "password"
            .form-group
              =f.check_box :remember_me, class: "form-check"
              =f.label :remember_me, "Remember me", class: "form-check-label"
            =f.submit "Login", class:"btn btn-info submit-btn"
        %br
        %p or
        = link_to  "Login as guest", guest_sessions_path, method: :post, class:"btn btn-secondary btn-block"