config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home", :to => "static_pages#home"
  get  "/signup", :to => "users#new"
  post "/signup", :to => "users#create"
  get "/graph",  :to => "users#graph"
  get    "/login", :to => "sessions#new"
  post   "/login", :to => "sessions#create"
  delete "/logout", :to => "sessions#destroy"
  resources :users do
    get :search, :on => :collection
    member do
      get :following, :followers
    end
  end
  resources :microposts, :only => [:create, :destroy, :edit, :update]
  resources :account_activations, :only => [:edit]
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :events
  resources :subjects
  resources :relationships, :only => [:create, :destroy]
  resources :likes, :only => [:create, :destroy]
  resources :guest_sessions, :only => [:create]
end

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger.alert-form-extend{:role => "alert"}
      = @user.errors.count
      errors.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.haml
- if @feed_items.any?
  .page-control= paginate @feed_items
  %ol.microposts
    = render @feed_items

app/views/shared/_graph.html.haml
.container.figure-container
  %h2.graph-title Report
  .figure-sum-and-button.row
    %span.figure-sum-text.col-sm
      %div.total-time
        Total：
        %em.figure-sum= sum_times
        minute
        (
        %em.figure-sum= to_hour
        hour)
    %span.dropdown.col-sm.period-button
      %button#dropdownMenuButton.btn.btn-info.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
        = @user.microposts_period(@period).keys.first
        \- #{@user.microposts_period(@period).keys.last}
      .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
        = link_to "Week", user_path(@user, period: "week"), class: "dropdown-item"
        = link_to "Month", user_path(@user, period: "month"), class: "dropdown-item"
        = link_to "Year", user_path(@user, period: "year"), class: "dropdown-item"
  = line_chart @chart, discrete: true, colors: ["#3eaeca"]

app/views/shared/_micropost_form.html.haml
= form_with(model: @micropost, remote: true) do |f|
  = render "shared/error_messages", object: f.object
  .field.title-form
    = f.text_field :title, class: "form-control", placeholder: "title", id: "title-form"
  .field.time-form
    = f.number_field :time, class: "form-control", placeholder: "time", id: "time-form"
  .field.content-form
    = f.text_area :content, class: "form-control", placeholder: "memo", id: "content-form"

  = f.submit "Post", class: "btn btn-block btn-info"

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.following.count
    following
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/shared/_user_info.html.haml
- if current_user == @user
  .user_image= link_to picture_for_user_info(current_user, size: 50), current_user
- else
  .user_image= link_to picture_for_user_info(@user, size: 50), @user
%h1.user-left-name= @user.name
%span#log-count= pluralize(@user.microposts.count, "post")