config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "home", :to => "static_pages#home"
  get  "/signup", :to => "users#new"
  post "/signup", :to => "users#create"
  get "/graph",  :to => "users#graph"
  get    "/login", :to => "sessions#new"
  post   "/login", :to => "sessions#create"
  delete "/logout", :to => "sessions#destroy"
  resources :users do
    get :search, :on => :collection
    member do
      get :following, :followers
    end
  end
  resources :microposts, :only => [:create, :destroy, :edit, :update]
  resources :account_activations, :only => [:edit]
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :events
  resources :subjects
  resources :relationships, :only => [:create, :destroy]
  resources :likes, :only => [:create, :destroy]
  resources :guest_sessions, :only => [:create]
end

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-default
  .container
    = link_to image_tag("logo.png", width: 70), root_path, class: "logo"
    %nav.navbar.navbar-expand
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li= render "layouts/search", class: "nav-link"
          %i.fa.fa-home.fa-xs
          %li.nav-item= link_to "Home", home_path, class: "nav-link"
          %i.fa.fa-file-text-o.fa-xs
          %li.nav-item= link_to "Subjects", subjects_path, class: "nav-link"
          %i.fa.fa-calendar.fa-xs
          %li.nav-item= link_to "Events", events_path, class: "nav-link"
          %i.fa.fa-line-chart.fa-xs
          %li.nav-item= link_to "Chart", graph_path, class: "nav-link"
          %i.fa.fa-user.fa-xs
          %li.nav-item= link_to "My page", user_path(current_user), class: "nav-link"
        - if logged_in?
          %i.fa.fa-cog.fa-xs
          %li.dropdown
            %li.dropdown
              %a.dropdown-toggle.header-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li.nav-item= link_to "Settings", edit_user_path(current_user), class: "nav-link"
                %li.divider
                %li.nav-item
                  = link_to "Logout", logout_path, method: :delete, class: "nav-link"
        - else
          %li.nav-item= link_to "Login", login_path, class: "nav-link"

app/views/layouts/_search.html.haml
.input-group
  = form_with(url: search_users_path, method: :get, local: true) do |f|
    = f.text_field :name, placeholder: "Search User", class: "form-control form-box"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "https://www.gstatic.com/charts/loader.js"
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.css", :rel => "stylesheet"}
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}
  %body
    .container
    = render "layouts/header"
    - flash.each do |message_type, message|
      = tag.div message, class: "alert alert-#{message_type}"
    = yield